
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=C5BFA1F74A1B58F76ED861A83697CEFB

[StartupActions]
bAddPacks=False
InsertPack=(PackSource="StarterContent.upack",PackName="StarterContent")

[SectionsToSave]
+Section=StartupActions

[/Script/LastDance.LDNetworkSettings]
;ServerAddress=127.0.0.1:7777